name: Release V1
on:
  push:
    tags:
      - v*
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.0"
      - name: Checkout Source Code
        uses: actions/checkout@v2
      - name: Build Go binary
        run: |
          VERSION=$(git describe --tags)
          FILENAME="gott-$VERSION-linux-amd64"
          CGO_ENABLED=0 go build -ldflags "-X main.version=$VERSION"
          strip -s gott
          mv gott $FILENAME
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}